use plaques;
db.dropDatabase();

db.plaquesLocations.insertMany([
  {
    "id":51313,"erected_at":null,"latitude":56.05785,"longitude":-2.6654,"updated_at":"2019-03-03T17:32:57.775Z","inscription":"In Memory of W. Edgar Evans B.Sc. FRSE, Founder and Scoutmaster, Donor of Canty Bay, 1883-1963, 2 TIM 22","is_current":true,"uri":"http://openplaques.org/plaques/51313","title":"Bronze plaque № 51313","address":"","subjects":null,"colour_name":"bronze","machine_tag":"openplaques:id=51313","geolocated?":true,"photographed?":true,"thumbnail_url":"https://s3.geograph.org.uk/geophotos/02/30/77/2307727_1879cfd0_120x120.jpg","photos":[{"uri":"http://openplaques.org/photos/31388.json","thumbnail_url":"https://s3.geograph.org.uk/geophotos/02/30/77/2307727_1879cfd0_120x120.jpg","shot_name":null,"attribution":"\u0026copy; Richard West on Geograph CC BY-SA 2.0"}],"organisations":[],"language":{"name":"English","alpha2":"en"},"area":{"name":" North Berwick","uri":"http://openplaques.org/places/gb/areas/north_berwick.json","country":{"name":"United Kingdom","alpha2":"gb","uri":"http://openplaques.org/places/gb.json"}},"people":[],"see_also":[]},
  {
    "id":49595,"erected_at":"2013-02-23","latitude":49.49775,"longitude":-2.5074,"updated_at":"2018-06-18T21:46:49.499Z","inscription":"Major Marie Ozanne O.F. Salvation Army 1906-1943 a resister to oppression  lived here","is_current":true,"uri":"http://openplaques.org/plaques/49595","title":"Marie Ozanne blue plaque","address":"Aquarius, Dehus Lane","subjects":"Marie Ozanne","colour_name":"blue","machine_tag":"openplaques:id=49595","geolocated?":true,"photographed?":true,"thumbnail_url":"https://farm2.staticflickr.com/1735/41075276380_3d3ff7cc6e_m.jpg","photos":[{"uri":"http://openplaques.org/photos/51573.json","thumbnail_url":"https://farm2.staticflickr.com/1735/41075276380_3d3ff7cc6e_m.jpg","shot_name":null,"attribution":"\u0026copy; Nick Harrison on Flickr CC BY-NC-SA 2.0"}],"organisations":[{"name":"Guernsey Museums","uri":"https://openplaques.org/organisations/guernsey_museums.json"}],"language":{"name":"English","alpha2":"en"},"area":{"name":" Vale, Guernsey","uri":"http://openplaques.org/places/gb/areas/vale_guernsey.json","country":{"name":"United Kingdom","alpha2":"gb","uri":"http://openplaques.org/places/gb.json"}},"people":[{"uri":"http://openplaques.org/people/16723.json","full_name":"Marie Ozanne"}],"see_also":[{"uri":"http://openplaques.org/plaques/39640"}]},
  {
    "id":41936,"erected_at":null,"latitude":50.51017,"longitude":-3.61166,"updated_at":"2016-09-28T07:15:40.057Z","inscription":"Abbotskerswell Cottage Art School was founded in this cottage c1883 by owner of Allervale Art Pottery and champion of the Arts and Crafts Movement John Phillips. This plaque was erected by Torquay Pottery Collectors Society in appreciation of those who taught and those who learnt here and the wondrous work they did.","is_current":true,"uri":"http://openplaques.org/plaques/41936","title":"Abbotskerswell Cottage Art School and John Phillips black plaque","address":"","subjects":"Abbotskerswell Cottage Art School and John Phillips","colour_name":"black","machine_tag":"openplaques:id=41936","geolocated?":true,"photographed?":true,"thumbnail_url":"https://s1.geograph.org.uk/geophotos/01/61/45/1614553_67858e1e_120x120.jpg","photos":[{"uri":"http://openplaques.org/photos/30051.json","thumbnail_url":"https://s1.geograph.org.uk/geophotos/01/61/45/1614553_67858e1e_120x120.jpg","shot_name":"close up","attribution":"\u0026copy; Derek Harper on Geograph CC BY-SA 2.0"},{"uri":"http://openplaques.org/photos/39911.json","thumbnail_url":"https://s2.geograph.org.uk/geophotos/01/61/45/1614546_7d4830ce_120x120.jpg","shot_name":"establishing shot","attribution":"\u0026copy; Derek Harper on Geograph CC BY-SA 2.0"},{"uri":"http://openplaques.org/photos/30849.json","thumbnail_url":"https://s1.geograph.org.uk/geophotos/02/80/87/2808793_3c94cbf0_120x120.jpg","shot_name":"establishing shot","attribution":"\u0026copy; David Smith on Geograph CC BY-SA 2.0"}],"organisations":[{"name":"Torquay Pottery Collectors Society","uri":"https://openplaques.org/organisations/torquay_pottery_collectors_society.json"}],"language":{"name":"English","alpha2":"en"},"area":{"name":"Abbotskerswell","uri":"http://openplaques.org/places/gb/areas/abbotskerswell.json","country":{"name":"United Kingdom","alpha2":"gb","uri":"http://openplaques.org/places/gb.json"}},"people":[{"uri":"http://openplaques.org/people/18894.json","full_name":"Abbotskerswell Cottage Art School"},{"uri":"http://openplaques.org/people/18895.json","full_name":"John Phillips"}],"see_also":[]}
])
